name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 20 (LTS and CI-compatible)
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Clean npm cache
        run: npm cache clean --force

      - name: Configure npm registry
        run: npm config set registry https://registry.npmjs.org/

      - name: Install dependencies safely
        run: npm install --legacy-peer-deps || npm install --force

      - name: Run tests
        run: npx jest --coverage
